### ISSUE TITLE
Should we use a template engine?

### ISSUE THREAD

**Issue by dylan-hachmann** [bradrn/wlhs#7]
I've gone ahead and made a proof-of-concept jinja2 template to demonstrate why we might want this.
https://github.com/dylan-hachmann/wlhs/commit/abf31ca049ab132bc8ba1567f8f008cd670c5450

Please take a look at [Pointer.hsc.jinja](https://github.com/dylan-hachmann/wlhs/blob/template-poc/utils/templates/Pointer.hsc.jinja). It's 164 lines versus the original 269+16 lines of comments. Personally, I find that it is much quicker and easier to produce than the rendered version. It's also less prone to some [hard-to-spot errors](https://github.com/dylan-hachmann/wlhs/blob/template-poc/src/WLR/Types/Pointer.hsc#L277).

I used jinja2 because it's what I'm familiar with, and I wanted to just get something worked out. I saw several template engines for use with Haskell (e.g. [heterocephalus](https://github.com/arowM/heterocephalus), [haiji](https://github.com/notogawa/haiji)), but I don't think anything that I looked at supports something like jinja2 macros, which are pretty useful here. Don't get me wrong though; I _would_ like to use Haskell and keep this project constrained to a single language, so long as we're able to find a reasonable alternative.

I've attached the rendered version, if you would like to take a look:
[RenderedPointer.txt](https://github.com/bradrn/wlhs/files/13855324/RenderedPointer.txt)
If you want to render it yourself, make sure to `pip install jinja2` and then just run `python3 render.py` from the directory it's in.

Would anyone else be interested in something like this?

**Comment by bradrn** [comment]
> I've gone ahead and made a proof-of-concept jinja2 template to demonstrate why we might want this.
> [dylan-hachmann@abf31ca](https://github.com/dylan-hachmann/wlhs/commit/abf31ca049ab132bc8ba1567f8f008cd670c5450)

I can certainly see why we might want this. And this implementation looks pretty good! I would definitely prefer *writing* these templated files over the original `Storable` instances.

What most worries me about this is the extra complexity it adds. Now the Haskell files need to undergo two different preprocessing steps — one to apply the templating, and one to run hsc2hs. If we can figure out a way to run it all transparently on `cabal build`, I would be happy to adopt this approach. But otherwise I’d be reluctant to use it.

**Comment by bradrn** [comment]
After a bit of exploring, it looks like [`ginger`](https://hackage.haskell.org/package/ginger) exists as a Haskell reimplementation of Jinja2, which would be much more convenient. I’ll see if I can use it together with your templates.

**Comment by dylan-hachmann** [comment]
Awesome, I'm glad you're on board! And yeah, complexity is no doubt a worry with these things. I've seen some jinja templates that make you wonder if they do more harm than good. I think that one big principle to follow is to try and minimize looping and conditionals in the template, keeping that to individually dissect-able macros.

Nice find with `ginger`; it definitely seems suitable!

**Comment by bradrn** [comment]
It looks like `ginger` lets you implement your own functions in Haskell, so I think that would be strongly preferable to including macros. That all depends on getting it to work, though…

**Comment by bradrn** [comment]
I’ve rewritten your macros using `ginger`: https://github.com/bradrn/wlhs/commit/b538b68528abe002a88dffd8bf745ced4892a127. It doesn’t support all the data structures of Jinja2 so I’ve had to make the functions take variable arguments, but otherwise it seems to work as far as I can tell.

(Also, it doesn’t format the output particularly nicely, but that’s fine because it will be incorporated into the Cabal preprocessor anyway.)

**Comment by bradrn** [comment]
I’ve incorporated the template macros into `Setup.hs`! Now, any `hsc` file can use these `ginger` macros, and they’re expanded on `cabal build` just like regular hsc2hs directives. The only work left to do now is to rewrite the existing files to use these new macros.

While I was at it, I also modified the macros to generate the Haskell name from the C name. So they now look like this:

https://github.com/bradrn/wlhs/blob/fbeef5f7336d1c0c2cdcd101cdf6c65643f5e41e/src/WL/ServerCore.hsc#L16-L27

**Comment by dylan-hachmann** [comment]
Awesome! I think that this all looks good. My only suggestion is that we run `column` on the

**Comment by bradrn** [comment]
…on the what?

**Comment by dylan-hachmann** [comment]
Oops, didn't even realize I hit enter! 😅

On the rows with two entries. Just find it much easier to look at. For example:
```
    "link",   "Ptr WL_list",
    "notify", "FunPtr WL_notify_func_t"
```

**Comment by bradrn** [comment]
I’m not actively opposed to that style, but I don’t prefer it either: I’ve been moving away from using that much vertical alignment.

**Comment by BurningWitness** [comment]
> Now, any hsc file can use these ginger macros, and they’re expanded on cabal build just like regular hsc2hs directives.

I don't think the level you're applying this on is correct. Templating should create a version of a library on <ins>your</ins> machine which <ins>you</ins> then commit, and then the difference between it and the previous version will be directly visible on the git diff. Delegating it onto the user means you both lose that cool diff history and force them to do extra busy work with extra dependencies for effectively no good reason.

**Comment by bradrn** [comment]
In that case, how would you recommend setting up such a template system? I dislike the idea of tracking every file in a duplicated form, once as a template and once as a macroexpanded file. (Which in any case will be expanded further by hsc2hs.)

**Comment by BurningWitness** [comment]
You will have to have it as a separate package inside the repository that you use to generate the bindings. I have on in `vulkan-raw`, there's one in `gl`, probably every single large project does this.

> I dislike the idea of tracking every file in a duplicated form.

The generation should be pure anyway (unless you want to debug stuff that silently failed on the user side), you're really just saving compilation time.

**Comment by dylan-hachmann** [comment]
> You will have to have it as a separate package inside the repository that you use to generate the bindings.

I'm not opposed to this. We'll just have to make it clear in the README that the rendered files are not to be hand-edited.

**Comment by bradrn** [comment]
> I have on in `vulkan-raw`, there's one in `gl`, probably every single large project does this.

The thing about projects like `vulkan-raw` and `gl` is that they can be *completely* autogenerated from a single XML file. There is no need to manually write anything at all — the whole of the library can be generated without manual intervention.

By contrast, libwayland and wlroots have no such all-encompassing specification. So they have to be written manually in any case. The templating system discussed in this issue is really just a couple of macros to abbreviate some definitions. Conceptually, it’s no different to hsc2hs, which everyone seems happy to use.

That being said, your earlier point about dependencies is a valid one. I’ll see if I can rewrite the current templating system to use only boot libraries.
